from app.model.majiang_model import MahjongTile, MahjongHand, MahjongWinChecker

print('=== 测试听牌算法 is_ready_hand ===')
print()

print('测试1：123456789万 + 11条 + 东（13张，听东风和1条）===')
hand = MahjongHand()
for i in range(1, 10):
    hand.add_tile(MahjongTile('wan', i))
hand.add_tile(MahjongTile('tiao', 1))
hand.add_tile(MahjongTile('tiao', 1))
hand.add_tile(MahjongTile('feng', 1))
print(f'手牌数量: {hand.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand.tiles]}')
is_ready, waiting = MahjongWinChecker.is_ready_hand(hand)
print(f'是否听牌: {is_ready}')
print(f'听牌: {[str(t) for t in waiting]}')
print()

print('测试2：1112345678999万 + 2条（13张，听2条）===')
hand2 = MahjongHand()
for i in range(1, 10):
    hand2.add_tile(MahjongTile('wan', i))
hand2.add_tile(MahjongTile('wan', 1))
hand2.add_tile(MahjongTile('wan', 1))
hand2.add_tile(MahjongTile('wan', 9))
hand2.add_tile(MahjongTile('wan', 9))
hand2.add_tile(MahjongTile('tiao', 2))
print(f'手牌数量: {hand2.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand2.tiles]}')
is_ready, waiting = MahjongWinChecker.is_ready_hand(hand2)
print(f'是否听牌: {is_ready}')
print(f'听牌: {[str(t) for t in waiting]}')
print()

print('测试3：11223344556677万（14张，七对子）===')
hand3 = MahjongHand()
for i in range(1, 8):
    hand3.add_tile(MahjongTile('wan', i))
    hand3.add_tile(MahjongTile('wan', i))
print(f'手牌数量: {hand3.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand3.tiles]}')
is_hu = MahjongWinChecker.is_winning_hand(hand3)
print(f'是否胡牌: {is_hu}')
print()

print('测试4：112233445566万 + 7万（13张，七对子听7万）===')
hand4 = MahjongHand()
for i in range(1, 7):
    hand4.add_tile(MahjongTile('wan', i))
    hand4.add_tile(MahjongTile('wan', i))
hand4.add_tile(MahjongTile('wan', 7))
print(f'手牌数量: {hand4.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand4.tiles]}')
is_ready, waiting = MahjongWinChecker.is_ready_hand(hand4)
print(f'是否听牌: {is_ready}')
print(f'听牌: {[str(t) for t in waiting]}')
print()

print('测试5：111222333万 + 44条 + 5条（13张，听5条）===')
hand5 = MahjongHand()
for _ in range(3):
    hand5.add_tile(MahjongTile('wan', 1))
    hand5.add_tile(MahjongTile('wan', 2))
    hand5.add_tile(MahjongTile('wan', 3))
for _ in range(2):
    hand5.add_tile(MahjongTile('tiao', 4))
hand5.add_tile(MahjongTile('tiao', 5))
print(f'手牌数量: {hand5.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand5.tiles]}')
is_ready, waiting = MahjongWinChecker.is_ready_hand(hand5)
print(f'是否听牌: {is_ready}')
print(f'听牌: {[str(t) for t in waiting]}')
print()

print('测试6：11123456789万 + 55条（13张，听1和9万）===')
hand6 = MahjongHand()
for i in range(1, 10):
    hand6.add_tile(MahjongTile('wan', i))
hand6.add_tile(MahjongTile('wan', 1))
hand6.add_tile(MahjongTile('wan', 1))
hand6.add_tile(MahjongTile('tiao', 5))
hand6.add_tile(MahjongTile('tiao', 5))
print(f'手牌数量: {hand6.get_tile_count()}')
print(f'手牌: {[str(t) for t in hand6.tiles]}')
is_ready, waiting = MahjongWinChecker.is_ready_hand(hand6)
print(f'是否听牌: {is_ready}')
print(f'听牌: {[str(t) for t in waiting]}')
