/**
 * 黄昏峡谷关卡
 * 主题：橙红色峡谷，日落时分
 * 特色：移动的阴影平台，需要把握时机
 */

import type { PlatformConfig, MovingPlatformConfig, OneWayPlatformConfig } from '@/entities/platform'
import type { TrapConfig, SpikeTrapConfig, SawTrapConfig, FireTrapConfig } from '@/entities/trap'
import type { CollectibleConfig } from '@/entities/collectible'
import type { LightZoneConfig } from '@/entities/light'
import type { ShadowZoneConfig } from '@/entities/light'
import type { TorchConfig } from '@/entities/torch'
import type { Vector2 } from '@/utils/math'
import type { LevelData } from './forest'

/**
 * 黄昏峡谷关卡数据
 */
export const canyonLevel: LevelData = {
  id: 2,
  name: '黄昏峡谷',
  description: '夕阳染红了峡谷，移动的平台在光影间穿梭。把握时机，跳跃穿越这片危险的峡谷。',
  difficulty: 2,
  width: 3000,
  height: 720,
  targetTime: 150,
  background: {
    backgroundColor: '#8B4513',
    parallaxFactor: 0.4,
  },
  spawnPoint: { x: 100, y: 550 },
  exitPoint: { x: 2900, y: 200 },

  platforms: [
    {
      type: 'normal',
      position: { x: 0, y: 620 },
      size: { width: 350, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 800, y: 620 },
      size: { width: 150, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 1300, y: 550 },
      size: { width: 120, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 1750, y: 620 },
      size: { width: 150, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 2200, y: 450 },
      size: { width: 120, height: 30 },
      collidable: true,
    },
    {
      type: 'oneWay',
      position: { x: 2500, y: 350 },
      size: { width: 100, height: 20 },
      collidable: true,
      passThroughThreshold: 10,
    },
    {
      type: 'normal',
      position: { x: 2750, y: 250 },
      size: { width: 250, height: 30 },
      collidable: true,
    },
  ],

  movingPlatforms: [
    {
      type: 'moving',
      position: { x: 400, y: 550 },
      size: { width: 120, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 400, y: 550, pauseTime: 1 },
        { x: 700, y: 550, pauseTime: 1 },
      ],
      speed: 100,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 1000, y: 480 },
      size: { width: 100, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 1000, y: 500, pauseTime: 0.5 },
        { x: 1000, y: 380, pauseTime: 0.5 },
      ],
      speed: 80,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 1450, y: 480 },
      size: { width: 130, height: 25 },
      collidable: true,
      mode: 'loop',
      path: [
        { x: 1450, y: 480, pauseTime: 0.8 },
        { x: 1600, y: 400, pauseTime: 0.8 },
        { x: 1450, y: 320, pauseTime: 0.8 },
        { x: 1300, y: 400, pauseTime: 0.8 },
      ],
      speed: 90,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 1950, y: 520 },
      size: { width: 110, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 1950, y: 520, pauseTime: 1.2 },
        { x: 2150, y: 520, pauseTime: 1.2 },
      ],
      speed: 120,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 2350, y: 380 },
      size: { width: 100, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 2350, y: 380, pauseTime: 0.6 },
        { x: 2350, y: 280, pauseTime: 0.6 },
      ],
      speed: 100,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 2650, y: 280 },
      size: { width: 90, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 2650, y: 280, pauseTime: 0.5 },
        { x: 2650, y: 180, pauseTime: 0.5 },
      ],
      speed: 110,
      autoStart: true,
    },
  ],

  traps: [
    {
      type: 'spike',
      position: { x: 350, y: 680 },
      size: { width: 450, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 20,
      spikeHeight: 25,
    },
    {
      type: 'saw',
      position: { x: 1150, y: 450 },
      size: { width: 50, height: 50 },
      damage: 1,
      active: true,
      startPoint: { x: 1150, y: 550 },
      endPoint: { x: 1150, y: 350 },
      speed: 120,
      radius: 25,
      rotationSpeed: 8,
    },
    {
      type: 'spike',
      position: { x: 1650, y: 680 },
      size: { width: 100, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 5,
      spikeHeight: 25,
    },
    {
      type: 'fire',
      position: { x: 1900, y: 600 },
      size: { width: 60, height: 20 },
      damage: 1,
      active: true,
      cycleTime: 2.5,
      activeDuration: 1.2,
      startDelay: 0.5,
      flameHeight: 70,
    },
    {
      type: 'saw',
      position: { x: 2100, y: 500 },
      size: { width: 50, height: 50 },
      damage: 1,
      active: true,
      startPoint: { x: 2050, y: 450 },
      endPoint: { x: 2300, y: 450 },
      speed: 150,
      radius: 25,
      rotationSpeed: 10,
    },
    {
      type: 'spike',
      position: { x: 2350, y: 680 },
      size: { width: 400, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 18,
      spikeHeight: 25,
    },
  ],

  collectibles: [
    {
      type: 'lightParticle',
      position: { x: 180, y: 520 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 550, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 870, y: 520 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1000, y: 330 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1360, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1450, y: 270 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1820, y: 520 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2050, y: 450 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2260, y: 380 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2350, y: 230 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2550, y: 280 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2700, y: 130 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2850, y: 180 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 550, y: 380 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1700, y: 450 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2400, y: 550 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'health',
      position: { x: 1360, y: 380 },
      size: 15,
      score: 0,
      attractRadius: 60,
      attractSpeed: 250,
      collectRadius: 20,
    },
    {
      type: 'star',
      position: { x: 1450, y: 200 },
      size: 14,
      score: 500,
      attractRadius: 100,
      attractSpeed: 350,
      collectRadius: 30,
    },
    {
      type: 'star',
      position: { x: 2650, y: 120 },
      size: 14,
      score: 500,
      attractRadius: 100,
      attractSpeed: 350,
      collectRadius: 30,
    },
  ],

  lightZones: [
    {
      position: { x: 180, y: 500 },
      size: { width: 200, height: 200 },
      shape: 'rectangle',
      speedMultiplier: 1.6,
      jumpMultiplier: 1.3,
      glowColor: '#FF8C00',
      glowIntensity: 0.8,
    },
    {
      position: { x: 550, y: 450 },
      size: { width: 150, height: 150 },
      shape: 'circle',
      speedMultiplier: 1.5,
      jumpMultiplier: 1.4,
      glowColor: '#FF8C00',
      glowIntensity: 0.9,
    },
    {
      position: { x: 1000, y: 430 },
      size: { width: 180, height: 180 },
      shape: 'ellipse',
      speedMultiplier: 1.6,
      jumpMultiplier: 1.3,
      glowColor: '#FF8C00',
      glowIntensity: 0.8,
    },
    {
      position: { x: 1820, y: 500 },
      size: { width: 160, height: 160 },
      shape: 'circle',
      speedMultiplier: 1.7,
      jumpMultiplier: 1.4,
      glowColor: '#FF8C00',
      glowIntensity: 0.9,
    },
    {
      position: { x: 2550, y: 280 },
      size: { width: 180, height: 200 },
      shape: 'rectangle',
      speedMultiplier: 1.6,
      jumpMultiplier: 1.3,
      glowColor: '#FF8C00',
      glowIntensity: 0.8,
    },
    {
      position: { x: 2800, y: 180 },
      size: { width: 200, height: 180 },
      shape: 'ellipse',
      speedMultiplier: 1.5,
      jumpMultiplier: 1.2,
      glowColor: '#FF8C00',
      glowIntensity: 0.8,
    },
  ],

  shadowZones: [
    {
      position: { x: 700, y: 550 },
      size: { width: 150, height: 150 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.7,
    },
    {
      position: { x: 1200, y: 450 },
      size: { width: 120, height: 200 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.7,
    },
    {
      position: { x: 1600, y: 400 },
      size: { width: 140, height: 140 },
      shape: 'circle',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.8,
    },
    {
      position: { x: 2100, y: 520 },
      size: { width: 100, height: 180 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.7,
    },
    {
      position: { x: 2400, y: 350 },
      size: { width: 130, height: 130 },
      shape: 'ellipse',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.7,
    },
    {
      position: { x: 2700, y: 230 },
      size: { width: 120, height: 120 },
      shape: 'circle',
      allowPhasing: true,
      glowColor: '#9932CC',
      glowIntensity: 0.8,
    },
  ],

  torches: [],
}
