/**
 * 午夜城堡关卡
 * 主题：深蓝色古堡，夜晚
 * 特色：可移动火把，主动创造光影路径
 */

import type { PlatformConfig, MovingPlatformConfig, OneWayPlatformConfig } from '@/entities/platform'
import type { TrapConfig, SpikeTrapConfig, SawTrapConfig, FireTrapConfig } from '@/entities/trap'
import type { CollectibleConfig } from '@/entities/collectible'
import type { LightZoneConfig } from '@/entities/light'
import type { ShadowZoneConfig } from '@/entities/light'
import type { TorchConfig } from '@/entities/torch'
import type { Vector2 } from '@/utils/math'
import type { LevelData } from './forest'

/**
 * 午夜城堡关卡数据
 */
export const castleLevel: LevelData = {
  id: 3,
  name: '午夜城堡',
  description: '夜幕笼罩着古老的城堡，利用可移动的火把照亮前路，创造属于你的光影通道。',
  difficulty: 3,
  width: 3000,
  height: 720,
  targetTime: 180,
  background: {
    backgroundColor: '#0A0A2A',
    parallaxFactor: 0.3,
  },
  spawnPoint: { x: 100, y: 550 },
  exitPoint: { x: 2900, y: 550 },

  platforms: [
    {
      type: 'normal',
      position: { x: 0, y: 620 },
      size: { width: 300, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 400, y: 620 },
      size: { width: 150, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 650, y: 550 },
      size: { width: 120, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 850, y: 480 },
      size: { width: 100, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 1050, y: 550 },
      size: { width: 150, height: 30 },
      collidable: true,
    },
    {
      type: 'oneWay',
      position: { x: 1250, y: 450 },
      size: { width: 100, height: 20 },
      collidable: true,
      passThroughThreshold: 10,
    },
    {
      type: 'normal',
      position: { x: 1400, y: 620 },
      size: { width: 200, height: 100 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 1700, y: 550 },
      size: { width: 120, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 1900, y: 480 },
      size: { width: 100, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 2100, y: 400 },
      size: { width: 120, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 2300, y: 480 },
      size: { width: 100, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 2500, y: 550 },
      size: { width: 150, height: 30 },
      collidable: true,
    },
    {
      type: 'normal',
      position: { x: 2700, y: 620 },
      size: { width: 300, height: 100 },
      collidable: true,
    },
  ],

  movingPlatforms: [
    {
      type: 'moving',
      position: { x: 1500, y: 500 },
      size: { width: 100, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 1500, y: 500, pauseTime: 1 },
        { x: 1500, y: 380, pauseTime: 1 },
      ],
      speed: 70,
      autoStart: true,
    },
    {
      type: 'moving',
      position: { x: 2000, y: 350 },
      size: { width: 90, height: 25 },
      collidable: true,
      mode: 'pingPong',
      path: [
        { x: 2000, y: 350, pauseTime: 0.8 },
        { x: 2200, y: 350, pauseTime: 0.8 },
      ],
      speed: 80,
      autoStart: true,
    },
  ],

  traps: [
    {
      type: 'spike',
      position: { x: 300, y: 680 },
      size: { width: 100, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 5,
      spikeHeight: 25,
    },
    {
      type: 'spike',
      position: { x: 550, y: 680 },
      size: { width: 100, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 5,
      spikeHeight: 25,
    },
    {
      type: 'fire',
      position: { x: 770, y: 600 },
      size: { width: 60, height: 20 },
      damage: 1,
      active: true,
      cycleTime: 3,
      activeDuration: 1.5,
      startDelay: 0,
      flameHeight: 65,
    },
    {
      type: 'saw',
      position: { x: 950, y: 500 },
      size: { width: 50, height: 50 },
      damage: 1,
      active: true,
      startPoint: { x: 950, y: 580 },
      endPoint: { x: 950, y: 420 },
      speed: 100,
      radius: 25,
      rotationSpeed: 9,
    },
    {
      type: 'spike',
      position: { x: 1200, y: 680 },
      size: { width: 200, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 10,
      spikeHeight: 25,
    },
    {
      type: 'fire',
      position: { x: 1600, y: 600 },
      size: { width: 80, height: 20 },
      damage: 1,
      active: true,
      cycleTime: 2.5,
      activeDuration: 1.2,
      startDelay: 0.8,
      flameHeight: 70,
    },
    {
      type: 'saw',
      position: { x: 1800, y: 500 },
      size: { width: 50, height: 50 },
      damage: 1,
      active: true,
      startPoint: { x: 1750, y: 520 },
      endPoint: { x: 1950, y: 520 },
      speed: 130,
      radius: 25,
      rotationSpeed: 10,
    },
    {
      type: 'spike',
      position: { x: 2050, y: 680 },
      size: { width: 150, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 8,
      spikeHeight: 25,
    },
    {
      type: 'fire',
      position: { x: 2400, y: 600 },
      size: { width: 70, height: 20 },
      damage: 1,
      active: true,
      cycleTime: 3.5,
      activeDuration: 1.8,
      startDelay: 0.3,
      flameHeight: 75,
    },
    {
      type: 'spike',
      position: { x: 2650, y: 680 },
      size: { width: 50, height: 40 },
      damage: 1,
      active: true,
      spikeCount: 3,
      spikeHeight: 25,
    },
  ],

  collectibles: [
    {
      type: 'lightParticle',
      position: { x: 150, y: 520 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 470, y: 520 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 710, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 900, y: 410 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1120, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1300, y: 380 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1500, y: 550 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1760, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1950, y: 410 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2160, y: 330 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2350, y: 410 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2570, y: 480 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2800, y: 550 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 350, y: 450 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1000, y: 350 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 1500, y: 320 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2100, y: 280 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'lightParticle',
      position: { x: 2750, y: 450 },
      size: 12,
      score: 100,
      attractRadius: 80,
      attractSpeed: 300,
      collectRadius: 25,
    },
    {
      type: 'health',
      position: { x: 1500, y: 420 },
      size: 15,
      score: 0,
      attractRadius: 60,
      attractSpeed: 250,
      collectRadius: 20,
    },
    {
      type: 'health',
      position: { x: 2500, y: 450 },
      size: 15,
      score: 0,
      attractRadius: 60,
      attractSpeed: 250,
      collectRadius: 20,
    },
    {
      type: 'star',
      position: { x: 2160, y: 260 },
      size: 14,
      score: 500,
      attractRadius: 100,
      attractSpeed: 350,
      collectRadius: 30,
    },
  ],

  lightZones: [
    {
      position: { x: 150, y: 500 },
      size: { width: 180, height: 180 },
      shape: 'rectangle',
      speedMultiplier: 1.5,
      jumpMultiplier: 1.3,
      glowColor: '#E6E6FA',
      glowIntensity: 0.8,
    },
    {
      position: { x: 900, y: 430 },
      size: { width: 140, height: 140 },
      shape: 'circle',
      speedMultiplier: 1.6,
      jumpMultiplier: 1.4,
      glowColor: '#E6E6FA',
      glowIntensity: 0.9,
    },
    {
      position: { x: 1500, y: 500 },
      size: { width: 160, height: 160 },
      shape: 'ellipse',
      speedMultiplier: 1.5,
      jumpMultiplier: 1.3,
      glowColor: '#E6E6FA',
      glowIntensity: 0.8,
    },
    {
      position: { x: 2160, y: 330 },
      size: { width: 150, height: 150 },
      shape: 'circle',
      speedMultiplier: 1.6,
      jumpMultiplier: 1.4,
      glowColor: '#E6E6FA',
      glowIntensity: 0.9,
    },
    {
      position: { x: 2800, y: 500 },
      size: { width: 180, height: 180 },
      shape: 'rectangle',
      speedMultiplier: 1.5,
      jumpMultiplier: 1.3,
      glowColor: '#E6E6FA',
      glowIntensity: 0.8,
    },
  ],

  shadowZones: [
    {
      position: { x: 600, y: 550 },
      size: { width: 120, height: 180 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.7,
    },
    {
      position: { x: 1050, y: 500 },
      size: { width: 100, height: 150 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.7,
    },
    {
      position: { x: 1300, y: 400 },
      size: { width: 120, height: 120 },
      shape: 'circle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.8,
    },
    {
      position: { x: 1750, y: 500 },
      size: { width: 100, height: 160 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.7,
    },
    {
      position: { x: 2000, y: 420 },
      size: { width: 110, height: 110 },
      shape: 'ellipse',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.7,
    },
    {
      position: { x: 2350, y: 420 },
      size: { width: 100, height: 140 },
      shape: 'rectangle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.7,
    },
    {
      position: { x: 2600, y: 500 },
      size: { width: 130, height: 130 },
      shape: 'circle',
      allowPhasing: true,
      glowColor: '#4B0082',
      glowIntensity: 0.8,
    },
  ],

  torches: [
    {
      position: { x: 200, y: 620 },
      size: { width: 20, height: 50 },
      baseLightRadius: 120,
      maxLightRadius: 180,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
    {
      position: { x: 700, y: 550 },
      size: { width: 20, height: 50 },
      baseLightRadius: 100,
      maxLightRadius: 160,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
    {
      position: { x: 1100, y: 550 },
      size: { width: 20, height: 50 },
      baseLightRadius: 110,
      maxLightRadius: 170,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
    {
      position: { x: 1450, y: 620 },
      size: { width: 20, height: 50 },
      baseLightRadius: 130,
      maxLightRadius: 190,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
    {
      position: { x: 1750, y: 550 },
      size: { width: 20, height: 50 },
      baseLightRadius: 100,
      maxLightRadius: 160,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: false,
    },
    {
      position: { x: 2150, y: 400 },
      size: { width: 20, height: 50 },
      baseLightRadius: 120,
      maxLightRadius: 180,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: false,
    },
    {
      position: { x: 2550, y: 550 },
      size: { width: 20, height: 50 },
      baseLightRadius: 110,
      maxLightRadius: 170,
      flameIntensity: 1,
      movable: true,
      rotatable: false,
      moveSpeed: 150,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
    {
      position: { x: 2800, y: 620 },
      size: { width: 20, height: 50 },
      baseLightRadius: 140,
      maxLightRadius: 200,
      flameIntensity: 1,
      movable: false,
      rotatable: false,
      moveSpeed: 0,
      rotationSpeed: 0,
      initialRotation: 0,
      initiallyLit: true,
    },
  ],
}
