from app.model.baoxiu.user import UserModel
from app.model.baoxiu.token import TokenModel
from app.model.baoxiu.student_detail import StudentDetailModel
from app.model.baoxiu.repairman_detail import RepairmanDetailModel
from app.model.baoxiu.order import OrderModel
from app.model.baoxiu.repair_record import RepairRecordModel
from app.model.baoxiu.dormitory import DormitoryModel
from app.model.baoxiu.notification import NotificationModel
from app.model.baoxiu.log import LogModel
